### ISSUE TITLE
'int_roll' and 'ext_roll'

### ISSUE THREAD

**Issue by Tianxzzz** [RManLuo/GSNOP#2]
In the data downloaded from the Google Cloud Disk link you gave, both edge.csv and label.csv files include a column of values' int_roll'. However, it is not in the original data. May I ask how the column of ’int_roll‘ is generated

**Comment by Tianxzzz** [comment]
By the way，your code works most of the time, but i got the 
(1) result:ap:0.0331  mrr:0.652  when run python train_np.py --data WIKI_0.1 --config config/TGAT.yml --base_model origin --eval_neg_samples 50 
(2)and result:ap:0.03667 mrr:0.6454 when run python train_np.py --data WIKI_0.3 --config config/TGAT.yml --base_model origin --eval_neg_samples 50.
(3)Run python train_np.py --data REDDIT_0.1 --config config/DySAT.yml --base_model origin --eval_neg_samples 50. I got AP: 0.5856, test mrr:-1.000
and so on
These results are always like this, so i think it's not the problem caused by random numbers/factors.

**Comment by RManLuo** [comment]
Hi, thanks for your interest in our work. Our framework is mainly based on [amazon-science/tgl](https://github.com/amazon-science/tgl). As a result, we adhere to the same data format. The detailed explanation of `int_roll` can be found at amazon-science/tgl#3. But, we do not use it in our experiments.

**Comment by Tianxzzz** [comment]
Thank you again for your answer which helped me a lot!
